class AccountInformationLocators:
    PAGE_SECTION = "information"
    RETURN_BUTTON = "return_button"
    EDIT_BUTTON = "edit_button"
    UNBIND_BUTTON = "unbind_button"
    CANCEL_BUTTON = "cancel"
    BIND_CLOUD = "bind_cloud"
    ACCOUNT_RENAME = "account_rename"
    UNBIND_TITLE = "unbind_title"
    SURE_BUTTON = "sure"
    NUT_CLOUD_BIND = "nut_cloud_bind"
    ACCOUNT_INPUT = "account_input"
    DELETE_NAME = "delete_name"
    CANCEL_RENAME = "cancel_rename"
    SURE_RENAME = "sure_rename"
