class DocumentHomeLocators:
    PAGE_SECTION = "cloud"
    DRIVE = "drive"
    SEARCH = "search"
    DOWNLOAD = "download"
    REFRESH = "refresh"
    SETUP = "setup"
    JAN_GRID_CHB = "jan_grid_chb"
    JAN_GRID_TV = "jan_grid_tv"
    FILE_GRID_TV = "file_grid_tv"
    JAN_LIST_NAME_TV = "jan_list_name_tv"
    DD_DRIVE = "dd_drive"
    ROOT_LAYOUT = "root_layout"
    STATUS_GRID_TV = "status_grid_tv"
    PRE_PAGE = "pre_page"
    NEXT_PAGE = "next_page"
    PAGE_TV = "page_tv"
    TV_ACCOUNT = "tv_account"
