class SearchCopyPageLocators:
    PAGE_SECTION = "copy"
    NEW_FOLDER = "new_folder"
    TV_FOLDER_NAME = "tv_folder_name"
    RB_SELECT = "rb_select"
    PAGE_LEFT = "page_left"
    PAGE_RIGHT = "page_right"
    PAGE_TV = "page_tv"
    DIALOG_CANCEL = "dialog_cancel"
    DIALOG_SURE = "dialog_sure"
    BT_ENTER = "bt_enter"
    JAN_NEW_FILE_TV = "janNewfileTv"
    NICK_NAME_CANCEL = "nickNamecancel"
    DIALOG_TITLE = "dialog_title"
    ROOT_ITEM_LAYOUT = "rootItemLayout"
    TV_RACK_NIMBLE = "tvRack_nimble"
